version: '3'

services:
  clickhouse:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - env
    volumes:
    - ./data:/var/lib/grafana:rw

  